[pytest]
addopts = -v --browser chromium --browser firefox --browser webkit --alluredir=allure-results --allure-pytest-auto-config=allure_pytest_auto.toml --tracing=retain-on-failure
testpaths = tests
markers = 
        smoke: quick sanity checks across the core flow
        regression: full detailed coverage